FROM centos:7
MAINTAINER sunwenju

RUN yum install -y gcc wget gcc-c++ make kernel-devel kernel-headers \
    openssl-devel pcre-devel gd-devel \
    iproute net-tools telnet wget curl unzip perl kernel-headers kernel-devel vim && \
    yum clean all && \
    rm -rf /var/cache/yum/* && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN cd /root && \
 wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u141-b15/336fa29ff2bb4ef291e347e091f7f4a7/jdk-8u141-linux-x64.tar.gz" && \
 tar zxf jdk-8u141-linux-x64.tar.gz  && \
 mv jdk1.8.0_141  /usr/local/jdk
RUN cd /root && \
  wget https://mirrors.tuna.tsinghua.edu.cn/apache/zookeeper/zookeeper-3.4.14/zookeeper-3.4.14.tar.gz && \
  tar zxf zookeeper-3.4.14.tar.gz && \
  mv  zookeeper-3.4.14  /usr/local/zookeeper && \
  mv /usr/local/zookeeper/conf/zoo_sample.cfg /usr/local/zookeeper/conf/zoo.cfg

RUN wget https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.3.1/jmx_prometheus_javaagent-0.3.1.jar && \
    mkdir /usr/local/jmx && \
    mv jmx_prometheus_javaagent-0.3.1.jar /usr/local/jmx
COPY zookeeper.yaml /usr/local/jmx

ENV JAVA_HOME=/usr/local/jdk
ENV JRE_HOME=$JAVA_HOME/jre
ENV CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar:$JRE_HOME/lib:$CLASSPATH
ENV PATH=/sbin:$JAVA_HOME/bin:$PATH
ENV JVMFLAGS="$JVMFLAGS -javaagent:/usr/local/jmx/jmx_prometheus_javaagent-0.3.1.jar=2182:/usr/local/jmx/zookeeper.yaml"
RUN rm -rf /root/*

WORKDIR /usr/local/zookeeper
COPY run.sh /tmp/run.sh
RUN chmod +x /tmp/run.sh
EXPOSE 2181 2182
CMD ["/tmp/run.sh"]
